#!/usr/bin/env python3
"""
Curated Ligand-Receptor Pair Analysis Across Four Breast Cancer Patients
========================================================================

Computes L-R interaction fold changes between first and last biopsy timepoints
and generates per-patient curated bar plots.

Input:  LR_Scores_AllPatients_AllTimepoints.csv
        (generated by LR_Temporal_AllPatients_Fast.R)
Output: Per-patient curated bar plots (PDF)
        Combined summary table (CSV)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# =============================================================================
# Paths
# =============================================================================

DATA_PATH = Path("supplementary_input_data/LR_Scores")
OUTPUT_PATH = Path("Figure7_Patient_Heatmaps")
OUTPUT_PATH.mkdir(parents=True, exist_ok=True)

# =============================================================================
# Colors
# =============================================================================

COLOR_UP = '#D4A017'    # Gold for increase
COLOR_DOWN = '#1B4F72'  # Dark blue for decrease

# =============================================================================
# Curated L-R Pairs Per Patient
# =============================================================================
# Selected based on: (1) known roles in breast cancer biology,
# (2) validated signaling pathways, (3) effect size.

PATIENT_CONFIG = {
    'A': {
        'first_tp': 'Bx2',
        'last_tp': 'Bx4',
        'pairs': {
            'Fibroblast\u2192Cancer': ['VTN\u2192ITGB8', 'HGF\u2192MET', 'FN1\u2192ITGB1'],
            'Myeloid\u2192Cancer': ['SPP1\u2192CD44', 'CXCL9\u2192DPP4', 'IL1A\u2192IL1RAP'],
            'Cancer Autocrine': ['WNT5A\u2192FZD4', 'AREG\u2192EGFR', 'MIF\u2192CD74'],
            'TCell\u2192Cancer': ['IFNG\u2192IFNGR1', 'FASLG\u2192FAS', 'TNF\u2192FAS'],
            'Endothelial\u2192Cancer': ['BMP4\u2192BMPR1A', 'NRG1\u2192EGFR', 'FGF2\u2192FGFR2'],
        }
    },
    'B': {
        'first_tp': 'Bx1',
        'last_tp': 'Bx4',
        'pairs': {
            'Fibroblast\u2192Cancer': ['COL6A1\u2192ITGB1', 'COL3A1\u2192DDR1', 'COL1A1\u2192DDR1'],
            'Myeloid\u2192Cancer': ['SPP1\u2192ITGB6', 'S100A9\u2192TLR4', 'VEGFA\u2192KDR'],
            'Cancer Autocrine': ['WNT5B\u2192FZD8', 'TGFB2\u2192TGFBR2', 'MIF\u2192CXCR4'],
            'TCell\u2192Cancer': ['IL2\u2192IL2RB', 'TNF\u2192LTBR', 'GZMB\u2192IGF2R', 'CD40LG\u2192ITGB1'],
            'Endothelial\u2192Cancer': ['CXCL12\u2192ITGB1', 'BMP4\u2192ACVR1'],
        }
    },
    'C': {
        'first_tp': 'Bx1',
        'last_tp': 'Bx2',
        'pairs': {
            'Fibroblast\u2192Cancer': ['THBS1\u2192CD36', 'THBS1\u2192ITGB1', 'COL1A1\u2192DDR1'],
            'Myeloid\u2192Cancer': ['SPP1\u2192ITGB5', 'SPP1\u2192ITGA5', 'FN1\u2192ITGA2'],
            'Cancer Autocrine': ['CDH1\u2192IGF1R', 'IGF1\u2192IGF1R', 'WNT7B\u2192FZD1', 'AREG\u2192ERBB3'],
            'TCell\u2192Cancer': ['IL2\u2192IL2RA', 'IFNG\u2192IFNGR2', 'IFNG\u2192IFNGR1'],
            'Endothelial\u2192Cancer': ['EFNA1\u2192EPHA3', 'FGF2\u2192FGFR2'],
        }
    },
    'D': {
        'first_tp': 'Bx1',
        'last_tp': 'Bx3',
        'pairs': {
            'Fibroblast\u2192Cancer': ['TIMP1\u2192CD63', 'VTN\u2192ITGA3', 'COL4A2\u2192ITGA1'],
            'Myeloid\u2192Cancer': ['FN1\u2192ITGA3', 'S100A9\u2192ALCAM', 'THBS1\u2192CD36'],
            'Cancer Autocrine': ['MIF\u2192CD74', 'WNT7B\u2192WIF1', 'IGF2\u2192IGF2R'],
            'TCell\u2192Cancer': ['LTB\u2192LTBR', 'TNF\u2192LTBR', 'FASLG\u2192FAS'],
            'Endothelial\u2192Cancer': ['EFNB2\u2192EPHB3', 'CXCL12\u2192ITGB1', 'JAG1\u2192NOTCH1'],
        }
    },
}

# =============================================================================
# Load Data
# =============================================================================

print("Loading L-R scores...")
scores_df = pd.read_csv(DATA_PATH / "LR_Scores_AllPatients_allTimepoints.csv")
scores_df['Patient'] = scores_df['Patient'].str.replace('Patient_', '')
print(f"  {len(scores_df)} score entries across {scores_df['Patient'].nunique()} patients")

# =============================================================================
# Compute Fold Changes for Curated Pairs
# =============================================================================

def compute_curated_fc(patient, first_tp, last_tp, curated_pairs):
    """Compute log2 fold change for curated L-R pairs.

    For each pair, FC = log2((Score_late + 0.001) / (Score_early + 0.001))
    where Score = Ligand_Mean * Receptor_Mean in the specified cell type context.
    """
    patient_data = scores_df[
        (scores_df['Patient'] == patient) &
        (scores_df['Timepoint'].isin([first_tp, last_tp]))
    ].copy()

    results = []
    for context, pairs in curated_pairs.items():
        for pair in pairs:
            pair_data = patient_data[patient_data['LR_Pair'] == pair]
            if len(pair_data) == 0:
                print(f"  Warning: {pair} not found for Patient {patient}")
                continue

            first_score = pair_data[pair_data['Timepoint'] == first_tp]['Score'].values
            last_score = pair_data[pair_data['Timepoint'] == last_tp]['Score'].values

            if len(first_score) == 0 or len(last_score) == 0:
                continue

            fc = np.log2((last_score[0] + 0.001) / (first_score[0] + 0.001))
            results.append({
                'Patient': patient,
                'Context': context,
                'LR_Pair': pair,
                'Score_Early': first_score[0],
                'Score_Late': last_score[0],
                'Log2FC': fc,
                'Direction': 'UP' if fc > 0 else 'DOWN',
                'Timepoint_Early': first_tp,
                'Timepoint_Late': last_tp,
            })

    return pd.DataFrame(results)

# =============================================================================
# Generate Per-Patient Bar Plots
# =============================================================================

def create_curated_barplot(patient, first_tp, last_tp, curated_pairs):
    """Horizontal bar plot of curated L-R pair fold changes.

    Bars are grouped by cell type context with gaps between groups.
    Gold = increase, dark blue = decrease. FC values annotated at bar tips.
    """
    curated_df = compute_curated_fc(patient, first_tp, last_tp, curated_pairs)
    if len(curated_df) == 0:
        print(f"  No data for Patient {patient}")
        return curated_df

    contexts = list(curated_pairs.keys())

    fig, ax = plt.subplots(figsize=(8, 10))

    # Layout: stack bars with gaps between context groups
    y_positions = []
    y_labels = []
    y = 0
    context_mids = {}

    for context in contexts:
        ctx_data = curated_df[curated_df['Context'] == context].sort_values(
            'Log2FC', ascending=True
        )
        start_y = y
        for _, row in ctx_data.iterrows():
            y_positions.append(y)
            y_labels.append(row['LR_Pair'])
            y += 1
        if len(ctx_data) > 0:
            context_mids[context] = (start_y + y - 1) / 2
        y += 1.5  # gap between contexts

    # Draw bars
    for _, row in curated_df.iterrows():
        idx = y_labels.index(row['LR_Pair'])
        y_pos = y_positions[idx]
        color = COLOR_UP if row['Log2FC'] > 0 else COLOR_DOWN
        ax.barh(y_pos, row['Log2FC'], height=0.7, color=color,
                edgecolor='white', linewidth=0.5)

        # FC label at bar tip
        offset = 0.1 if row['Log2FC'] > 0 else -0.1
        ha = 'left' if row['Log2FC'] > 0 else 'right'
        ax.text(row['Log2FC'] + offset, y_pos, f"{row['Log2FC']:+.1f}",
                va='center', ha=ha, fontsize=9, fontweight='bold')

    ax.set_yticks(y_positions)
    ax.set_yticklabels(y_labels, fontsize=10)

    # Context labels on right side
    max_x = max(curated_df['Log2FC'].max() + 1, 1)
    for context, mid_y in context_mids.items():
        ax.text(max_x + 0.8, mid_y, context, va='center', ha='left',
                fontsize=10, fontweight='bold')

    ax.axvline(0, color='black', linewidth=1)
    ax.set_xlabel(f'Log2 Fold Change ({last_tp} / {first_tp})', fontsize=11)
    ax.set_title(f'Patient {patient}: Selected L-R Pairs\n({first_tp} \u2192 {last_tp})',
                 fontsize=13, fontweight='bold')

    xlim = ax.get_xlim()
    ax.set_xlim(min(xlim[0], -1) - 0.5, max(xlim[1], 1) + 0.5)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    outfile = OUTPUT_PATH / f'Patient{patient}_Curated_BarPlot.pdf'
    plt.savefig(outfile, bbox_inches='tight', dpi=300)
    plt.close()
    print(f"  Saved: {outfile.name}")

    return curated_df

# =============================================================================
# Run Analysis
# =============================================================================

print("=" * 60)
print("Generating curated L-R bar plots for all patients")
print("=" * 60)

all_curated = []
for patient, config in PATIENT_CONFIG.items():
    print(f"\nPatient {patient} ({config['first_tp']} \u2192 {config['last_tp']}):")
    df = create_curated_barplot(patient, config['first_tp'],
                                config['last_tp'], config['pairs'])
    if len(df) > 0:
        all_curated.append(df)

# Combine and save summary
summary_df = pd.concat(all_curated, ignore_index=True)
summary_file = OUTPUT_PATH / 'AllPatients_Curated_LR_Summary.csv'
summary_df.to_csv(summary_file, index=False)
print(f"\nSummary saved: {summary_file.name}")
print(f"  {len(summary_df)} curated pairs across {summary_df['Patient'].nunique()} patients")

# Per-patient summary
print("\n" + "=" * 60)
print("Summary")
print("=" * 60)
for patient in ['A', 'B', 'C', 'D']:
    pdf = summary_df[summary_df['Patient'] == patient]
    n_up = (pdf['Direction'] == 'UP').sum()
    n_down = (pdf['Direction'] == 'DOWN').sum()
    mean_fc = pdf['Log2FC'].mean()
    print(f"  Patient {patient}: {n_up} UP, {n_down} DOWN "
          f"(mean FC = {mean_fc:+.2f})")

print("\nDone!")
